### PR TITLE
Copy/Paste + import from HearthPwn.com

### PR DESCRIPTION
**Pull request by bmichotte**
Hello @Jeswang,

in this PR, I added the possibility to import decks from http://www.hearthpwn.com. To import a deck, simply use the tag from the url (http://www.hearthpwn.com/decks/158447-fakenicks-legend-1-eu-season-10-pala -> use 158447-fakenicks-legend-1-eu-season-10-pala or 158447) and this will import the deck. I also added an "edit" menu to allow copy/paste into the builder ID.

Btw, I added a "game language" combobox to allow to choose the language to display the deck into. This combobox should be removed in a futur commit where there will be a "settings" window to configure such things.

### CODE REVIEW

**Comment by Jeswang** [comment]
Cool.
It seems hard to merge storyboard, so I will create new window by creating nib files, how you do so.

I'm new to using the merge function, if I'm doing something wrong, you can tell me, thank you.

**Comment by Jeswang** [comment]
Agree with you about adding a setting dialog. 
Do you want I add you as Collaborators so we can commit in the same repo?

**Comment by bmichotte** [comment]
Hello,

You can add me with pleasure. But we need to be ok on the way you want to so things.

For storyboards and nibs, it's a pain. There is no easy way to keep them clean.

**Comment by Jeswang** [comment]
Do you use slack? We can talk more easily there.

**Comment by bmichotte** [comment]
I just installed it but never used. How does it work ?

**Comment by Jeswang** [comment]
What's your mail address? Tell me here or send message to wangyi724@gmail.com

**Comment by Jeswang** [comment]
Already send invitation to this mail address benjamin@produweb.be

**Pull request merged**
